title: CP Sheets
author: ahampriyanshu
description: Solving various CP/SDE sheets.
theme: jekyll-theme-leap-day
markdown: kramdown
highlighter: rouge
show_downloads: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed